Linux:
  Default:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: ./propores
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
  GUI:
    colours:
      description text: '#4F81BD'
      description title: '#4F81BD'
      section title: '#C0504D'
      sub-section title: '#76923D'
    fonts:
      check button:
      - Calibri
      - 10
      description text:
      - Calibri
      - 10
      description title:
      - Calibri
      - 14
      - bold
      entry field label:
      - Calibri
      - 10
      entry field text:
      - Calibri
      - 9
      file chooser button:
      - Calibri
      - 9
      option menu:
      - Calibri
      - 9
      radiobutton:
      - Calibri
      - 10
      run button:
      - Calibri
      - 9
      section title:
      - Calibri
      - 14
      - bold
      status line:
      - Calibri
      - 10
      sub-section title:
      - Calibri
      - 10
      - bold
      title check button:
      - Calibri
      - 14
      - bold
    heights:
      description frame: 1000
    styles:
      theme: clam
    widths:
      description frame: 400
      description text: 390
      file/directory chooser button: 3
      file/directory entry field: 30
      left settings button: 15
      number entry field: 15
      right settings button: 15
      run button: 20
      save/cancel button: 15
      separator line width: 1
      status box: 50
      status box border: 1
    x-margins:
      column: 20
      description text:
      - 0
      - 0
      description title:
      - 0
      - 0
      empty check button:
      - 10
      - 0
      entry field label:
      - 0
      - 10
      entry field text:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 0
      - 0
      separator:
      - 0
      - 0
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 0
      - 0
      window left: 5
      window right: 10
    y-margins:
      column:
      - 0
      - 0
      description text:
      - 0
      - 0
      description title:
      - 15
      - 0
      empty check button:
      - 0
      - 0
      entry field label:
      - 0
      - 0
      entry field text:
      - 2
      - 2
      field name:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 15
      - 0
      separator:
      - 10
      - 10
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 15
      - 0
      window bottom: 10
  User:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: ./propores
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
Mac OS X:
  Default:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: propores
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
  GUI:
    colours:
      description text: '#4F81BD'
      description title: '#4F81BD'
      section title: '#C0504D'
      sub-section title: '#76923D'
    fonts:
      check button:
      - Calibri
      - 12
      description text:
      - Calibri
      - 12
      description title:
      - Calibri
      - 16
      - bold
      entry field label:
      - Calibri
      - 12
      entry field text:
      - Calibri
      - 10
      file chooser button:
      - Calibri
      - 12
      option menu:
      - Calibri
      - 11
      radiobutton:
      - Calibri
      - 12
      run button:
      - Calibri
      - 12
      section title:
      - Calibri
      - 16
      - bold
      status line:
      - Calibri
      - 12
      sub-section title:
      - Calibri
      - 12
      - bold
      title check button:
      - Calibri
      - 16
      - bold
    heights:
      description frame: 1000
    styles:
      theme: aqua
    widths:
      description frame: 400
      description text: 390
      file/directory chooser button: 3
      file/directory entry field: 30
      left settings button: 15
      number entry field: 15
      right settings button: 15
      run button: 20
      save/cancel button: 15
      separator line width: 1
      status box: 50
      status box border: 1
    x-margins:
      column: 20
      description text:
      - 0
      - 0
      description title:
      - 0
      - 0
      empty check button:
      - 10
      - 0
      entry field label:
      - 0
      - 10
      entry field text:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 0
      - 0
      separator:
      - 0
      - 0
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 0
      - 0
      window left: 5
      window right: 10
    y-margins:
      column:
      - 0
      - 0
      description text:
      - 0
      - 0
      description title:
      - 15
      - 0
      empty check button:
      - 0
      - 0
      entry field label:
      - 0
      - 0
      entry field text:
      - 2
      - 2
      field name:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 15
      - 0
      separator:
      - 10
      - 10
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 15
      - 0
      window bottom: 20
  User:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: propores
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
Windows:
  Default:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: propores.exe
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
  GUI:
    colours:
      description text: '#4F81BD'
      description title: '#4F81BD'
      section title: '#C0504D'
      sub-section title: '#76923D'
    fonts:
      check button:
      - Calibri
      - 12
      description text:
      - Calibri
      - 11
      description title:
      - Calibri
      - 16
      - bold
      entry field label:
      - Calibri
      - 12
      entry field text:
      - Calibri
      - 10
      file chooser button:
      - Calibri
      - 11
      option menu:
      - Calibri
      - 11
      radiobutton:
      - Calibri
      - 12
      run button:
      - Calibri
      - 12
      section title:
      - Calibri
      - 16
      - bold
      status line:
      - Calibri
      - 12
      sub-section title:
      - Calibri
      - 12
      - bold
      title check button:
      - Calibri
      - 16
      - bold
    heights:
      description frame: 10000
    styles:
      theme: vista
    widths:
      description frame: 400
      description text: 390
      file/directory chooser button: 3
      file/directory entry field: 30
      left settings button: 15
      number entry field: 15
      right settings button: 15
      run button: 20
      save/cancel button: 15
      separator line width: 1
      status box: 50
      status box border: 1
    x-margins:
      column: 20
      description text:
      - 0
      - 0
      description title:
      - 0
      - 0
      empty check button:
      - 10
      - 0
      entry field label:
      - 0
      - 10
      entry field text:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 0
      - 0
      separator:
      - 0
      - 0
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 0
      - 0
      window left: 5
      window right: 10
    y-margins:
      column:
      - 0
      - 0
      description text:
      - 0
      - 0
      description title:
      - 15
      - 0
      empty check button:
      - 0
      - 0
      entry field label:
      - 0
      - 0
      entry field text:
      - 2
      - 2
      field name:
      - 0
      - 0
      file chooser button:
      - 0
      - 0
      left settings button:
      - 0
      - 0
      right settings button:
      - 0
      - 0
      run button:
      - 0
      - 0
      section title:
      - 15
      - 0
      separator:
      - 10
      - 10
      status box frame:
      - 0
      - 0
      subsection title:
      - 0
      - 0
      text check button:
      - 0
      - 0
      text separator:
      - 0
      - 0
      title check button:
      - 15
      - 0
      window bottom: 10
  User:
    Axis trace:
      axis selection: 0
      directory input: ''
      input selection: 0
      run: false
      run from input: false
      single input: ''
      surface patch threshold: 30.0
    Gate open:
      clash tolerance: 0.75
      difficulty: run all
      directory input: ''
      input selection: 0
      intput selection: 0
      re-estimate difficulty: false
      rotamer library: rotamer_lib/
      run: false
      single input: ''
    General:
      H atoms: keep all
      PDB path: input/1EA5_R.pdb
      PROPORES executable: propores.exe
      batch input: input/
      cores: 1
      hetero atoms: keep all
      input selection: 0
      keep alternative locations: false
      output directory: results/
      output name: ''
      skip non-std amino acids: false
    Pore ID:
      axis preparation: false
      computation mode: autodetect
      gate preparation: false
      pore filter: all
      pore types: all
      preparation: autodetect
      probe radius: 1.4
      resolution: 1.0
      run: true
      solvent radius: 1.2
      volume threshold: 50.0
